cmake_minimum_required(VERSION 4.1)

project(nedit
    LANGUAGES C 
    VERSION 1.0.1
    DESCRIPTION "Text editor made with C and GTK"
)

set(CMAKE_C_STANDARD 23)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)

cmake_pkg_config(IMPORT gtk4 REQUIRED NAME GTK4)

add_executable(${PROJECT_NAME}
    ${CMAKE_SOURCE_DIR}/src/app_data.c
    ${CMAKE_SOURCE_DIR}/src/app_data.h
    ${CMAKE_SOURCE_DIR}/src/dialog.c
    ${CMAKE_SOURCE_DIR}/src/dialog.h
    ${CMAKE_SOURCE_DIR}/src/file_util.c
    ${CMAKE_SOURCE_DIR}/src/file_util.h
    ${CMAKE_SOURCE_DIR}/src/main.c
    ${CMAKE_SOURCE_DIR}/src/main.h
    ${CMAKE_SOURCE_DIR}/src/main_window.ui
)

target_link_libraries(${PROJECT_NAME} PRIVATE PkgConfig::GTK4)

install(TARGETS ${PROJECT_NAME} RUNTIME)

set(CPACK_PACKAGE_VENDOR "Damareon Carter")
set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_SYSTEM_NAME ${CMAKE_SYSTEM_NAME})
set(CPACK_PACKAGE_FILE_NAME ${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CPACK_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR})
set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_SOURCE_DIR}/LICENSE.md)
set(CPACK_RESOURCE_FILE_README ${CMAKE_SOURCE_DIR}/README.md)
set(CPACK_STRIP_FILES TRUE)

include(CPack)